### ISSUE TITLE
【增强】希望增加定时自动取关功能和取关白名单功能

### ISSUE THREAD

**Issue by lhllhx** [tobycroft/BiliHP-APP#10]
把所有已经中奖的主播自动列为取关白名单
并且在设定的时间自动取关未在白名单中的主播

**Comment by tobycroft** [comment]
已经解决：https://github.com/tobycroft/BiliHP-APP/releases/tag/Android1.30.1

**Comment by tobycroft** [comment]
取关白名单功能已经更新

**Comment by tobycroft** [comment]
如果还是很需要自动取关，请reopen或者reissue
