### ISSUE TITLE
[增强]用户可以选择是否使用服务器推荐的天选屏蔽词黑名单和主播黑名单

### ISSUE THREAD

**Issue by lhllhx** [tobycroft/BiliHP-APP#12]
如题
添加一个开关或按钮使得用户可以选择是否把个人服务器推荐的黑名单导入到用户配置中，方便多账号管理

**Comment by tobycroft** [comment]
现在不是就已经可以导入了吗？最新版，你安卓还是苹果啊，苹果等TF更新，那边审核很慢的

**Comment by lhllhx** [comment]
我的意思是 在个人服务器里面保存一份天选屏蔽词列表 然后服务器中成员可以选择同步服务器里面的天选屏蔽词，这就不用有新的屏蔽词之后要每个账号一个个添加。

**Comment by tobycroft** [comment]
就是公共屏蔽词列表的意思是吧

**Comment by lhllhx** [comment]
是的

**Comment by tobycroft** [comment]
安排上了，后续版本中迭代更新……

**Comment by tobycroft** [comment]
不过最好说一下希望是什么样的，是从什么地方来分享的，个人设置页面还是什么页面来分享，分享的时候是一键分享还是分享的时候需要填写推荐理由，然后正常一个好的列表需要用户打分的，怎么打分才是公平科学的，诸如此类比较详细的想法

**Comment by lhllhx** [comment]
在服务器配置中写上屏蔽词，由服主维护 用户可以在个人配置界面中选择是否使用服务器配置，或者选择是否同步服务器配置（你看看哪种bug会少一点）

**Comment by tobycroft** [comment]
Feature已经解决

[https://github.com/tobycroft/BiliHP-APP/releases/tag/Android1.33.0](https://github.com/tobycroft/BiliHP-APP/releases/tag/Android1.33.0)
#https://github.com/tobycroft/BiliHP-APP/releases/tag/Android1.33.0
