### ISSUE TITLE
无法连接到服务器，问题如下

### ISSUE THREAD

**Issue by Iktsuarpok-L** [tobycroft/BiliHP-APP#15]
1、安卓App：
         输入账号密码登录时跳出空白模态框。
         服务器无限重连。
2、PCGo web端控制器：
         登录时alert了一个undefined，后面有登陆成功提示，顺便拒绝连接= =
3、PC.NET：
         em...短信验证等了半个点了

ps:  用App短信登录上了
啊，顺便问一下，自动送礼的小姐姐房间强制的？。。

**Comment by tobycroft** [comment]
………………………………

**Comment by tobycroft** [comment]
感谢这位大佬的测试反馈………………

**Comment by tobycroft** [comment]
昨天出现无限重连的问题是因为服务器程序掉线了，因为这次修改了新接口，可能在判断上部分值不是float64导致的，目前已经重启了，使用可以再观察一下

如上问题都是因为服务器炸裂导致的，现在都已经修复了

软件没有自动送礼功能，请注意，软件新装后是有一个默认房间的，可以通过APP的包裹/勋章列表来进行一键切换

**Comment by Iktsuarpok-L** [comment]
过奖了，咱就一臭打游戏的，面向百度编程

刚试了下pcgo web端，还是一样的localhost拒绝连接
看了network，ajax没问题是200，报错是localhost的document类型failed
我应该没缺文件吧，下了html，新建了conf.ini
跳转panel也无效

**Comment by tobycroft** [comment]
这个需要看下PCGo的返回

**Comment by tobycroft** [comment]
PCGo的界面上是什么返回呢，因为新版的PCGo是会自动创建conf.ini的，在没有conf的情况下第一次跳转会失败，第二次就会成功了

**Comment by Iktsuarpok-L** [comment]
还是拒绝连接请求，DOS直接自己关闭了
算求。。.net和c2c都能用。不纠结了。。

**Comment by tobycroft** [comment]
先用这两个吧
