### ISSUE TITLE
劫持节奏风暴

### ISSUE THREAD

**Issue by xiaohandk** [tobycroft/BiliHP-APP#17]
能否修改一下逻辑呢
优化一下抢到的概率（小声bb）
抢到节奏风暴以后，直接丢弃，不会重复一直领取
在上一个领取的过程中出现下一个节奏风暴，直接丢弃上一个或者不领取下一个，或同时出现两个节奏风暴，丢弃一个，防止412
只是建议哈，毕竟免费软件，没那么多要求，主要是412

**Comment by tobycroft** [comment]
这条我不知道怎么回，不好做吧，因为我没有抓到过领取成功的返回数据（2020版）是什么样的，另外因为这个是多线程的，如果是单线程的，那么是可以基于上一个返回来决定下一条的，因为我这边是多线程的模型。

这个模型是在程序接收到风暴信息后，先判断是否使用劫持模型，如果劫持，使用什么机构来做这个并发访问，然后多少数据量（并发/秒数）

在动作确定后，开始创建无监控的多线程，这个动作在接收到风暴信息后就已经确定好了

而且线程因为是无监控启停的，所以没有开关，这也导致一旦开始，就要执行完

对此，你可以通过降低执行秒数来解决并发问题，这是一个治标的方法
