### ISSUE TITLE
树莓派无法正常运行，疑似未编译为 arm 平台版本

### ISSUE THREAD

**Issue by JueLuo99** [tobycroft/BiliHP-APP#2]
已测试 ```PCGo0.22.8.7z``` 包内的文件置入树莓派后无法正常运行

执行 ```file BiliHP_PC_linux``` 可见如下回显

``` bash
BiliHP_PC_linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=cTMeMD7StRV-wejiWpTd/Lzn6YH5qgK5svXjAC-14/tsGjkthmQ9qCa4OmgpW0/tip56KKff_HaBT8bxBRc, not stripped
```

**Comment by tobycroft** [comment]
不不不，BiliHP的树莓派版本是ARM的那个，路由器是router版本那个注意区分，PC是x86版本电脑用的，如果没有找到可以直接使用C2CGo，使用C2C为主网贡献点弹幕23333

**Comment by tobycroft** [comment]
另外啊，PCGo好像有些打包里面没有ARM，所以主要关注下release，如果reslease里面没有arm的版本，可以自己编译，或者直接使用C2C就好了
