### ISSUE TITLE
pc net每天必定崩溃

### ISSUE THREAD

**Issue by just-automatic** [tobycroft/BiliHP-APP#22]
pc net每天必定崩溃, 今天甚至登陆上了之后不到一分钟必崩溃

**Comment by tobycroft** [comment]
截图看看，换PCGo试试，看下是不是网络问题

**Comment by just-automatic** [comment]
之前我就做过实验, 服务器上的net和笔记本上的net都同一时间崩溃, 不是网络问题, 然后net会生成崩溃日志之类的吗, 不然截图也看不到有用的信息啊

**Comment by just-automatic** [comment]
还有就是
<ol>
<li>有的时候莫名其妙就停止了和服务器的连接, 希望加入重连机制</li>
<li>输出信息要进行一下内存的释放, 不然信息多了之后清屏会引发内存泄露</li>
<li>需要重新登陆的时候可否自动登录, 因为在服务器上运行, 有了问题也不能第一时间发现</li>
</ol>
暂时就是这些

**Comment by tobycroft** [comment]
这个大概率是网络问题啊，程序是有重连机制的，后面出错的部分就是重连机制导致的。

出错的截图复制粘贴到issue来

内存释放是有做的，500条才会自动清空

自动登录会弹验证码，概率。自动过滑块验证我感觉做起来比较麻烦，每过段时间重新登录就好了。

**Comment by tobycroft** [comment]
这个大概率是网络问题啊，程序是有重连机制的，后面出错的部分就是重连机制导致的。

出错的截图复制粘贴到issue来

内存释放是有做的，500条才会自动清空

自动登录会弹验证码，概率。自动过滑块验证我感觉做起来比较麻烦，每过段时间重新登录就好了

**Comment by just-automatic** [comment]
emmmm因为昨天b站的改版属实disgusted me, 所以我把牌子都删了, 抱歉不能再提供什么有用的信息啦, 我关了issue吧
