### ISSUE TITLE
数据基本上修复完毕，丢失了部分重要数据

### ISSUE THREAD

**Issue by tobycroft** [tobycroft/BiliHP-APP#25]
服务器漏水导致硬盘电解水烧黑了，主板已经无法正常开机，SSD（程序盘）接口烧黑无法识别

经过一晚上的数据恢复，现在重要的程序盘两个服务器的镜像数据全部恢复

数据库因为是PCIE的，所以没有被电解水滴到，只要缓存阵列没有把主控带挂，数据库是可以救回的

目前新订购的主板以及双路主板，CPU已经在路上了

新的配件过几天就会寄到了，预计下周周末前应该就可以完成恢复

受灾图就发在群里了，如果要围观的可以首页查下群号

呐，我们之前是不接收捐款的，不过这次的话花费到目前为止已经超过2600元（新购）

欢迎有条件的朋友支援

**Comment by acooler15** [comment]
没有贴收款码

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/87904674-644c1d80-ca91-11ea-9831-9a091fc88258.png)
![image](https://user-images.githubusercontent.com/24893075/87904680-6ada9500-ca91-11ea-8323-cfeca4953b44.png)

**Comment by tobycroft** [comment]
新的设备已经好了，等待水冷组件到达

**Comment by tobycroft** [comment]
恩，数据库……不出意外的挂掉了……目前评估是B-级损失（B-级损失为数据出现部分缺失，大部分数据完好，但是需要重新构建）

目前BiliHP大概数据总量在几亿条，恢复起来略有困难，另外因为redis没有做aof（就算做了之前泡水估计也挂了），所以到时候肯定是需要重新登录的

另外BiliHP的数据库主键丢失了90%很头疼，而且这块数据只能我自己研究处理，不能把数据库的文件发给其他人帮忙研究（防止出现数据泄露的情况），所以我再去学习学习这块知识再做处理了，时间上如果快的话今晚能修好，修不好那就不确定什么时候能修好了

因为之前手贱关了自动备份系统，所以这次B-级的故障不好处理，我看下能出来多少数据吧

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/88248521-08250b80-ccd4-11ea-8a28-c9d644a03a77.png)
![image](https://user-images.githubusercontent.com/24893075/88248526-0b1ffc00-ccd4-11ea-9b5b-e1045eee740d.png)

**Comment by acooler15** [comment]
数据库损坏了？？？

**Comment by tobycroft** [comment]
> 数据库损坏了？？？

损坏了，数据库在启动的时候直接fail了，凉凉，怎么处理都是不行呢，准备重新安装然后倒入

**Comment by MaxwellXiao** [comment]
还能好吗？刚star就翻车了。。。

**Comment by tobycroft** [comment]
@MaxwellXiao 快了快的话今晚就能恢复了，因为数据库丢了然后现在数据量很大，正在想办法

**Comment by tobycroft** [comment]
服务器数据恢复中，目前只能暂时恢复主网

**Comment by tobycroft** [comment]
目前数据损失等级为“S”（S+为最顶级，SS为存储设备都坏的那种），数据无法恢复，只能通过急救数据恢复表结构，但是我们的程序里面有很多核心的数据在数据库中，这些数据都无法找回了，所以只能……你懂的，慢慢恢复吧

**Comment by tobycroft** [comment]
好的S+已经丢表了

**Comment by MaxwellXiao** [comment]
又挂了吗？我这里无法连接服务器了
