### ISSUE TITLE
服务器是炸了吗？cmd里在不停的刷连接故障……正在重连……

### ISSUE THREAD

**Issue by 2651084156** [tobycroft/BiliHP-APP#32]
haert 0
连接服务器失败！ dial tcp 120.35.40.248:181: connectex: No connection could be made because the target machine actively refused it.
连接故障……正在重连……
所有直播間已經停止監聽……
服务器发送失败，断线无法发送消息Main
消息无法发送到服务器
连接服务器失败！ dial tcp 120.35.40.248:181: connectex: No connection could be made because the target machine actively refused it.
连接故障……正在重连……
所有直播間已經停止監聽……
连接服务器失败！ dial tcp 120.35.40.248:181: connectex: No connection could be made because the target machine actively refused it.

**Comment by tobycroft** [comment]
昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了

**Comment by acooler15** [comment]
> 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了

10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)

我的不行啊。。。

**Comment by tobycroft** [comment]
> > 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了
> 
> 10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
> 
> 我的不行啊。。。

切换服务器就好了

**Comment by acooler15** [comment]
> > > 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了
> > 
> > 
> > 10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
> > 我的不行啊。。。
> 
> 切换服务器就好了

不行，切到IPV6的服务器，依然报错，切到超级节点2，提示“请在首页连入助手网络”。。。

**Comment by acooler15** [comment]
> > > 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了
> > 
> > 
> > 10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
> > 我的不行啊。。。
> 
> 切换服务器就好了

兔子，181端口开了没？

**Comment by tobycroft** [comment]
> > > > 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了
> > > 
> > > 
> > > 10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
> > > 我的不行啊。。。
> > 
> > 
> > 切换服务器就好了
> 
> 兔子，181端口开了没？

端口已经重新映射了，但是IPV6版本的没有映射，因为程序的话之前有绑定180和181的，但是我这边有几个退档，所以版本有点老，现在暂时先切过去了，先使用IPV4吧

**Comment by acooler15** [comment]
> > > > > 昨天的话路由器更新，所以网络重启，大概昨天晚上10点就弄好了
> > > > 
> > > > 
> > > > 10:4:34[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/110.83.33.236 (port 181) from /192.168.123.105 (port 42988) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
> > > > 我的不行啊。。。
> > > 
> > > 
> > > 切换服务器就好了
> > 
> > 
> > 兔子，181端口开了没？
> 
> 端口已经重新映射了，但是IPV6版本的没有映射，因为程序的话之前有绑定180和181的，但是我这边有几个退档，所以版本有点老，现在暂时先切过去了，先使用IPV4吧

可以了。

**Comment by tobycroft** [comment]
已经完成了啊，如果再有问题重新打开
