### ISSUE TITLE
最新版本是否支持安卓4

### ISSUE THREAD

**Issue by gili-gili** [tobycroft/BiliHP-APP#36]
miui9，安卓4，能够安装，但是打开一下后就会闪退

**Comment by tobycroft** [comment]
这么老的版本啊？

**Comment by gili-gili** [comment]
> 这么老的版本啊？

是的，有点特殊嘛......所以是支持还是不支持，不支持的话建议直接不允许安装得了0_0

**Comment by tobycroft** [comment]
最低我记得设定为6.0了，因为安卓市场的最低版本要求，所以要安卓8.0起，你可以刷机，XDA上面很多三方固件，Mi5都可以支持到安卓11呢

**Comment by gili-gili** [comment]
红米2A，算是锁死在安卓4了（捂脸）
