### ISSUE TITLE
服务器状况反馈

### ISSUE THREAD

**Issue by gili-gili** [tobycroft/BiliHP-APP#38]
18:8:25[BiliHP-ECAM(双击可复制)]：failed to connect to go.bilihp.com/59.61.160.85 (port 181) from /10.195.4.11 (port 36780) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)

似乎所有服务器都挂了，还是被墙了......

**Comment by tobycroft** [comment]
已经解决

**Comment by gili-gili** [comment]
2021-11-20,确认修复

**Comment by gili-gili** [comment]
2021-11-20 20:30,服务器又炸了

**Comment by tobycroft** [comment]
1

**Comment by gili-gili** [comment]
2021-10-21 10:45 確認恢復
