### ISSUE TITLE
app送礼模块有问题

### ISSUE THREAD

**Issue by lhllhx** [tobycroft/BiliHP-APP#4]
部分房间送礼时提示 参数错误（305）  
电脑端参加天选时也有问题  
![image](https://user-images.githubusercontent.com/52107206/81167494-e1561380-8fc7-11ea-82ad-6a44a1d64fc4.png)

**Comment by tobycroft** [comment]
参数错误是因为有些直播间在这个基础上，会有一些特殊的需求，比如要你送一个金瓜子礼物，或者让你送一个小电视才能抽奖，这类礼物就会出现这个问题，所以是正常的

**Comment by tobycroft** [comment]
程序只默认处理发弹幕这样的抽奖，如果涉及到要花钱或者送礼物的抽奖，就不会去送

**Comment by lhllhx** [comment]
![image](https://user-images.githubusercontent.com/52107206/81258340-069a5e80-9068-11ea-8ba6-28d77a8ff867.png)
还有是这个的问题 app手动送礼部分房间报错

**Comment by tobycroft** [comment]
部分直播间确实存在问题，需要独立分析，附上直播间号

**Comment by lhllhx** [comment]
870691

**Comment by tobycroft** [comment]
知道了，有能力的话帮忙抓个包，最近在忙IOS上架

**Comment by lhllhx** [comment]
我把自用的可行的送礼代码拉过来  
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/da813fd0cc19d41325088fa4dc8bdaaddbe9a686/Src/GiftSend.py#L27-L150  
你可以参考一下

**Comment by tobycroft** [comment]
又让我去抄代码，把我当什么人了

**Comment by tobycroft** [comment]
麻烦给一个PHP版本的参考谢谢（/狗头

**Comment by lhllhx** [comment]
https://github.com/metowolf/BilibiliHelper/blob/0.9x/src/plugins/GiftSend.php
~~我这里什么都有，就是什么都不会写~~
那个python版本据说是参考了这个版本的  
关键实现逻辑应该是一样的

**Comment by tobycroft** [comment]
麻烦给一个shell脚本写的，谢谢
(/滑稽

**Comment by tobycroft** [comment]
（礼貌性的表达想要拖更的意思

**Comment by tobycroft** [comment]
目前投票比较高的是”每日奖励统计“功能，送礼功能做了，然后按照亲密度送算是加强体验的功能，首先我不是结巴，然后这个功能暂时大概排期排在了下下下下下下下下期了

**Comment by lhllhx** [comment]
对了 如果想参与开发要怎么做 好像github没有源码

**Comment by tobycroft** [comment]
有哦~看下其他的repo

**Comment by tobycroft** [comment]
经过一个晚上的努力，本功能我表示做不了，Pass………你可以通过APP中的包裹列表直接赠送，有其他的需求可以再提
