### ISSUE TITLE
winPC桌面版银瓜子和签到任务无效

### ISSUE THREAD

**Issue by Memorywzd** [tobycroft/BiliHP-APP#5]
控制里面勾选了签到和在线银瓜子任务，实际上并没有参加，手动点击签到也没有正确签到，提示今日礼物已领取

**Comment by tobycroft** [comment]
你这个是啥版本啊，我记得在160版本前签到就全部独立出来了，最新版本1.13.0要注意更新

**Comment by Memorywzd** [comment]
就是1.13.0qaq
刚刚在隔壁听说大佬的软件很顶才来下载用的

**Comment by tobycroft** [comment]
要注意更新，我们的软件可能一天很多更，所以注意下release

**Comment by tobycroft** [comment]
功能确认没问题，注意保持在线，8小时会重复签到哦
