### ISSUE TITLE
c2c服务端停机报错

### ISSUE THREAD

**Issue by Memorywzd** [tobycroft/BiliHP-APP#6]
panic: runtime error: index out of range [54] with length 54

goroutine 77839 [running]:
main.go/Action/ActionRoute.SuperCurl.func2(0x982660, 0xc00005f0e0, 0x8d9fe8, 0x3, 0xc00048ecc0, 0x19, 0x60, 0x54d613, 0xc0000242c8, 0x85eb20)
E:/MyDoc/IdeaProject/BiliHP-C2CGo/Action/ActionRoute/SuperCurl.go:111 +0x161
net/http.(*Transport).dial(0xc0000a6500, 0x982660, 0xc00005f0e0, 0x8d9fe8, 0x3, 0xc00048ecc0, 0x19, 0x0, 0xc00020c810, 0xc0000fa240, ...)
C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1085 +0x1f5
net/http.(*Transport).dialConn(0xc0000a6500, 0x982660, 0xc00005f0e0, 0x0, 0xc0001d6540, 0x5, 0xc00048ecc0, 0x19, 0x0, 0xc0000fa360, ...)
C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1519 +0x19ee
net/http.(*Transport).dialConnFor(0xc0000a6500, 0xc00008c000)
C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1365 +0xc6
created by net/http.(*Transport).queueForDial
C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1334 +0x3fe
提示如上，服务器运行不超过24h必报错停机

**Comment by Memorywzd** [comment]
panic: runtime error: index out of range [54] with length 54

goroutine 77839 [running]:
main.go/Action/ActionRoute.SuperCurl.func2(0x982660, 0xc00005f0e0, 0x8d9fe8, 0x3, 0xc00048ecc0, 0x19, 0x60, 0x54d613, 0xc0000242c8, 0x85eb20)
        E:/MyDoc/IdeaProject/BiliHP-C2CGo/Action/ActionRoute/SuperCurl.go:111 +0x161
net/http.(*Transport).dial(0xc0000a6500, 0x982660, 0xc00005f0e0, 0x8d9fe8, 0x3, 0xc00048ecc0, 0x19, 0x0, 0xc00020c810, 0xc0000fa240, ...)
        C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1085 +0x1f5
net/http.(*Transport).dialConn(0xc0000a6500, 0x982660, 0xc00005f0e0, 0x0, 0xc0001d6540, 0x5, 0xc00048ecc0, 0x19, 0x0, 0xc0000fa360, ...)
        C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1519 +0x19ee
net/http.(*Transport).dialConnFor(0xc0000a6500, 0xc00008c000)
        C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1365 +0xc6
created by net/http.(*Transport).queueForDial
        C:/Users/Tuuz/sdk/go1.14.2/src/net/http/transport.go:1334 +0x3fe
提示如上，服务器运行不超过24h必报错停机

**Comment by Memorywzd** [comment]
环境为centos8.1 python3.6.8

**Comment by tobycroft** [comment]
收到了，BUG确认，解决后通知，不需要Python环境，建议C2C直接使用docker或者coreos纯净环境，稳定度会更高

**Comment by tobycroft** [comment]
[https://github.com/tobycroft/BiliHP-APP/releases/tag/C2C1.8.3](url)

新版去下载吧

**Comment by Memorywzd** [comment]
大大辛苦辣

**Comment by tobycroft** [comment]
https://github.com/tobycroft/BiliHP-APP/releases/tag/C2C1.8.4
