### ISSUE TITLE
服务器信息版本显示  牌子识别

### ISSUE THREAD

**Issue by MualaniMarine** [tobycroft/BiliHP-APP#7]

**Comment by tobycroft** [comment]
啥……啥意思……

**Comment by tobycroft** [comment]
[Android1.29.0](https://github.com/tobycroft/BiliHP-APP/releases/tag/Android1.29.0)

**Comment by tobycroft** [comment]
https://github.com/tobycroft/BiliHP-APP/releases/tag/PCNet1.16.0

https://github.com/tobycroft/BiliHP-APP/releases/tag/PCGo1.3.0

https://github.com/tobycroft/BiliHP-APP/releases/tag/PCGo1.3.0

https://github.com/tobycroft/BiliHP-APP/releases/tag/C2C1.9.6

做完了，点赞去
