### ISSUE TITLE
app服务器配置显示问题

### ISSUE THREAD

**Issue by lhllhx** [tobycroft/BiliHP-APP#9]
![TIM图片20200531190508](https://user-images.githubusercontent.com/52107206/83350866-aef2c880-a371-11ea-9886-e0a2a23282bd.jpg)
这几个显示有误，与事实不符

**Comment by tobycroft** [comment]
压缩等级是针对C2C有弹幕权限的节点的，功能启用这个没啥作用，如果要停止功能的话，直接关闭服务器会更好一点，是否展示这个我确认了下代码，并没有这个问题

**Comment by lhllhx** [comment]
是否展示可以观察已经公开的服务器 发现全部服务器都为否 
所以是否展示应该是有问题的

**Comment by tobycroft** [comment]
了解了

**Comment by tobycroft** [comment]
已经修复
